Numpy Arrays:
Creating an array from a list

In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
np.array(mylist)

array([1, 2, 3])

In [4]:
type(np.array(mylist))

numpy.ndarray

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

.arange is similar to range in python

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(2)

array([1., 1.])

np.ones((2,4))

.linspace() gives you evenly spaced numbers or values between a certain interval.

In [18]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [25]:
len(np.linspace(1,100,10))

10

.eye() is used to create an identity matrix

In [23]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.random.rand(1)

array([0.90731938])

In [29]:
np.random.rand(5,2)

array([[0.60661341, 0.67665642],
       [0.80916272, 0.69085751],
       [0.40944712, 0.81890198],
       [0.09693635, 0.59530054],
       [0.66830057, 0.9185691 ]])

.random.rand gives a uniform distributed number between 0 and 1, where 1 is exclusive

In [30]:
np.random.randn(2)

array([-1.46651469, -0.37362108])

.random.radn gives  standard distrubuted betweeen 0 and 1 thereby giving more values closer to 0

In [31]:
np.random.randn(2,3)

array([[ 1.11398285, -0.28173441,  0.56536735],
       [-0.27482348,  1.0098001 ,  0.73140705]])

In [32]:
np.random.randint(3)

2

.random.randint returns integars within a certain range

In [33]:
np.random.randint(0,101,(4,5))

array([[26,  9, 24,  2, 96],
       [60,  6, 56, 58,  9],
       [13, 50, 15, 70, 32],
       [65, 80,  6, 20, 45]])

Seed is used to set a random state so that as particular set of number can be obtained

In [35]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [36]:
arr= np.arange(0,25)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
ranarr = np.random.randint(0,101,10)

In [42]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [43]:
ranarr.max()

99

In [44]:
ranarr.min()

2

In [45]:
ranarr.argmax()

5

In [46]:
ranarr.argmin()

7