In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

broadcasting

In [8]:
arr[:5] = 100

In [9]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr = np.arange(0,11)

In [11]:
slice_of_arr = arr[:5]

In [12]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [13]:
slice_of_arr[:] = 99

In [14]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [15]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [16]:
arr_copy = arr.copy()

In [17]:
arr_copy[:]= 100

In [18]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [19]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [22]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])


In [23]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [24]:
arr_2d.shape

(3, 3)

In [25]:
arr[:2]

array([99, 99])

In [26]:
arr_2d[:3]

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [27]:
arr_2d[:]

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
arr = np.arange(1,11)

In [29]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [32]:
bool_arr = arr >4

In [33]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [34]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])